
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jonathan
 */
public class mainClass extends javax.swing.JFrame implements KeyListener{
    

    private Color lightRed = new Color(204,0,0);
    private Color red = new Color(153,0,0);
    private double simpleCurrentNum;
    private String simpleOperation;
    private double simpleLastNum;
    private double justOperatedNum;
    private boolean justOperated;
    private boolean justSwitchNeg;
    private boolean decimalMode;
    
    /**
     * Creates new form mainClass
     */
    public mainClass() {
        initComponents();
        leftPanel.addKeyListener(this);
        leftPanel.setFocusable(true);
        leftPanel.requestFocusInWindow();
        

        simpleCurrentNum = 0;
        simpleOperation = "+";
        simpleLastNum = 0;
        justOperatedNum = 0;
        justOperated = false;
        justSwitchNeg = false;
        decimalMode = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPanel = new javax.swing.JPanel();
        simpleButton = new javax.swing.JLabel();
        scientificButton = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        simpleCalc = new javax.swing.JPanel();
        lastNumDisplay = new javax.swing.JLabel();
        currentNumDisplay = new javax.swing.JLabel();
        buttonCE = new javax.swing.JLabel();
        buttonC = new javax.swing.JLabel();
        buttonDEL = new javax.swing.JLabel();
        buttonDivide = new javax.swing.JLabel();
        buttonMultiply = new javax.swing.JLabel();
        buttonSubtract = new javax.swing.JLabel();
        buttonAdd = new javax.swing.JLabel();
        buttonEquals = new javax.swing.JLabel();
        buttonNeg = new javax.swing.JLabel();
        buttonDecimal = new javax.swing.JLabel();
        button0 = new javax.swing.JLabel();
        button1 = new javax.swing.JLabel();
        button2 = new javax.swing.JLabel();
        button3 = new javax.swing.JLabel();
        button4 = new javax.swing.JLabel();
        button5 = new javax.swing.JLabel();
        button6 = new javax.swing.JLabel();
        button7 = new javax.swing.JLabel();
        button8 = new javax.swing.JLabel();
        button9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 0));
        setPreferredSize(new java.awt.Dimension(518, 542));
        setResizable(false);

        leftPanel.setBackground(new java.awt.Color(51, 51, 51));

        simpleButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        simpleButton.setForeground(new java.awt.Color(204, 0, 0));
        simpleButton.setText("   Simple");
        simpleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simpleButtonMouseClicked(evt);
            }
        });
        simpleButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                simpleButtonKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                simpleButtonKeyTyped(evt);
            }
        });

        scientificButton.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        scientificButton.setForeground(new java.awt.Color(204, 0, 0));
        scientificButton.setText("   Scientific");
        scientificButton.setPreferredSize(new java.awt.Dimension(94, 32));

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(simpleButton, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
            .addComponent(scientificButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(simpleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(scientificButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rightPanel.setBackground(new java.awt.Color(153, 0, 0));
        rightPanel.setPreferredSize(new java.awt.Dimension(350, 500));
        rightPanel.setLayout(new java.awt.CardLayout());

        simpleCalc.setBackground(new java.awt.Color(153, 0, 0));

        lastNumDisplay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lastNumDisplay.setForeground(new java.awt.Color(255, 255, 255));
        lastNumDisplay.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lastNumDisplay.setText("55,138 +  5,134 =  ");

        currentNumDisplay.setBackground(new java.awt.Color(255, 255, 255));
        currentNumDisplay.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        currentNumDisplay.setForeground(new java.awt.Color(153, 0, 0));
        currentNumDisplay.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        currentNumDisplay.setText("60,272  ");
        currentNumDisplay.setOpaque(true);

        buttonCE.setBackground(new java.awt.Color(153, 0, 0));
        buttonCE.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        buttonCE.setForeground(new java.awt.Color(255, 255, 255));
        buttonCE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonCE.setText("CE");
        buttonCE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        buttonCE.setOpaque(true);
        buttonCE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCEMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonCEMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonCEMouseReleased(evt);
            }
        });

        buttonC.setBackground(new java.awt.Color(153, 0, 0));
        buttonC.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        buttonC.setForeground(new java.awt.Color(255, 255, 255));
        buttonC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonC.setText("C");
        buttonC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        buttonC.setOpaque(true);
        buttonC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonCMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonCMouseReleased(evt);
            }
        });

        buttonDEL.setBackground(new java.awt.Color(153, 0, 0));
        buttonDEL.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        buttonDEL.setForeground(new java.awt.Color(255, 255, 255));
        buttonDEL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonDEL.setText("DEL");
        buttonDEL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        buttonDEL.setOpaque(true);
        buttonDEL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonDELMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonDELMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonDELMouseReleased(evt);
            }
        });

        buttonDivide.setBackground(new java.awt.Color(153, 0, 0));
        buttonDivide.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        buttonDivide.setForeground(new java.awt.Color(255, 255, 255));
        buttonDivide.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonDivide.setText("/");
        buttonDivide.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        buttonDivide.setOpaque(true);
        buttonDivide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonDivideMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonDivideMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonDivideMouseReleased(evt);
            }
        });

        buttonMultiply.setBackground(new java.awt.Color(153, 0, 0));
        buttonMultiply.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        buttonMultiply.setForeground(new java.awt.Color(255, 255, 255));
        buttonMultiply.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonMultiply.setText("*");
        buttonMultiply.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        buttonMultiply.setOpaque(true);
        buttonMultiply.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMultiplyMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonMultiplyMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonMultiplyMouseReleased(evt);
            }
        });

        buttonSubtract.setBackground(new java.awt.Color(153, 0, 0));
        buttonSubtract.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        buttonSubtract.setForeground(new java.awt.Color(255, 255, 255));
        buttonSubtract.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonSubtract.setText("-");
        buttonSubtract.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        buttonSubtract.setOpaque(true);
        buttonSubtract.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonSubtractMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonSubtractMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonSubtractMouseReleased(evt);
            }
        });

        buttonAdd.setBackground(new java.awt.Color(153, 0, 0));
        buttonAdd.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        buttonAdd.setForeground(new java.awt.Color(255, 255, 255));
        buttonAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonAdd.setText("+");
        buttonAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        buttonAdd.setOpaque(true);
        buttonAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAddMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonAddMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonAddMouseReleased(evt);
            }
        });

        buttonEquals.setBackground(new java.awt.Color(153, 0, 0));
        buttonEquals.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        buttonEquals.setForeground(new java.awt.Color(255, 255, 255));
        buttonEquals.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonEquals.setText("=");
        buttonEquals.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        buttonEquals.setOpaque(true);
        buttonEquals.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonEqualsMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonEqualsMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonEqualsMouseReleased(evt);
            }
        });

        buttonNeg.setBackground(new java.awt.Color(153, 0, 0));
        buttonNeg.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        buttonNeg.setForeground(new java.awt.Color(255, 255, 255));
        buttonNeg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonNeg.setText("+/-");
        buttonNeg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        buttonNeg.setOpaque(true);
        buttonNeg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonNegMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonNegMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonNegMouseReleased(evt);
            }
        });

        buttonDecimal.setBackground(new java.awt.Color(153, 0, 0));
        buttonDecimal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        buttonDecimal.setForeground(new java.awt.Color(255, 255, 255));
        buttonDecimal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buttonDecimal.setText(".");
        buttonDecimal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        buttonDecimal.setOpaque(true);
        buttonDecimal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonDecimalMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonDecimalMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonDecimalMouseReleased(evt);
            }
        });

        button0.setBackground(new java.awt.Color(153, 0, 0));
        button0.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        button0.setForeground(new java.awt.Color(255, 255, 255));
        button0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        button0.setText("0");
        button0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        button0.setOpaque(true);
        button0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button0MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button0MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                button0MouseReleased(evt);
            }
        });

        button1.setBackground(new java.awt.Color(153, 0, 0));
        button1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        button1.setText("1");
        button1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        button1.setOpaque(true);
        button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                button1MouseReleased(evt);
            }
        });

        button2.setBackground(new java.awt.Color(153, 0, 0));
        button2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        button2.setForeground(new java.awt.Color(255, 255, 255));
        button2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        button2.setText("2");
        button2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        button2.setOpaque(true);
        button2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                button2MouseReleased(evt);
            }
        });

        button3.setBackground(new java.awt.Color(153, 0, 0));
        button3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        button3.setForeground(new java.awt.Color(255, 255, 255));
        button3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        button3.setText("3");
        button3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        button3.setOpaque(true);
        button3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button3MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button3MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                button3MouseReleased(evt);
            }
        });

        button4.setBackground(new java.awt.Color(153, 0, 0));
        button4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        button4.setForeground(new java.awt.Color(255, 255, 255));
        button4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        button4.setText("4");
        button4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        button4.setOpaque(true);
        button4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button4MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button4MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                button4MouseReleased(evt);
            }
        });

        button5.setBackground(new java.awt.Color(153, 0, 0));
        button5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        button5.setForeground(new java.awt.Color(255, 255, 255));
        button5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        button5.setText("5");
        button5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        button5.setOpaque(true);
        button5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button5MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button5MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                button5MouseReleased(evt);
            }
        });

        button6.setBackground(new java.awt.Color(153, 0, 0));
        button6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        button6.setForeground(new java.awt.Color(255, 255, 255));
        button6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        button6.setText("6");
        button6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        button6.setOpaque(true);
        button6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button6MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button6MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                button6MouseReleased(evt);
            }
        });

        button7.setBackground(new java.awt.Color(153, 0, 0));
        button7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        button7.setForeground(new java.awt.Color(255, 255, 255));
        button7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        button7.setText("7");
        button7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        button7.setOpaque(true);
        button7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button7MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button7MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                button7MouseReleased(evt);
            }
        });

        button8.setBackground(new java.awt.Color(153, 0, 0));
        button8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        button8.setForeground(new java.awt.Color(255, 255, 255));
        button8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        button8.setText("8");
        button8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        button8.setOpaque(true);
        button8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button8MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button8MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                button8MouseReleased(evt);
            }
        });

        button9.setBackground(new java.awt.Color(153, 0, 0));
        button9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        button9.setForeground(new java.awt.Color(255, 255, 255));
        button9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        button9.setText("9");
        button9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        button9.setOpaque(true);
        button9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button9MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button9MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                button9MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout simpleCalcLayout = new javax.swing.GroupLayout(simpleCalc);
        simpleCalc.setLayout(simpleCalcLayout);
        simpleCalcLayout.setHorizontalGroup(
            simpleCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(currentNumDisplay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, simpleCalcLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(simpleCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonCE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonNeg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(simpleCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, simpleCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(simpleCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(button8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(simpleCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(simpleCalcLayout.createSequentialGroup()
                        .addComponent(buttonDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(buttonDEL, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(simpleCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(simpleCalcLayout.createSequentialGroup()
                            .addComponent(button9, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(buttonMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(simpleCalcLayout.createSequentialGroup()
                            .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(buttonSubtract, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, simpleCalcLayout.createSequentialGroup()
                            .addComponent(button0, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(buttonEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, simpleCalcLayout.createSequentialGroup()
                            .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addComponent(lastNumDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        simpleCalcLayout.setVerticalGroup(
            simpleCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(simpleCalcLayout.createSequentialGroup()
                .addComponent(lastNumDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(currentNumDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(simpleCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDEL, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonC, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCE, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(simpleCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button9, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(simpleCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSubtract, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(simpleCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(simpleCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonEquals, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button0, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonNeg, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        rightPanel.add(simpleCalc, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void simpleButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpleButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_simpleButtonMouseClicked

    private void simpleButtonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_simpleButtonKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_simpleButtonKeyTyped

    private void simpleButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_simpleButtonKeyPressed

    }//GEN-LAST:event_simpleButtonKeyPressed

    private void buttonEqualsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEqualsMouseClicked
        // TODO add your handling code here:
        
        if (justOperated == true) {
            lastNumDisplay.setText(simpleLastNum +" "+ simpleOperation + " "+justOperatedNum +" = ");
            simpleCurrentNum = justOperatedNum;
        }
        else {
            lastNumDisplay.setText(simpleLastNum +" "+ simpleOperation + " "+simpleCurrentNum +" = ");
        }
        if (simpleOperation.equals("+")) {
            if (justOperated == false) {
                justOperatedNum = simpleCurrentNum;
                
            }
            
            simpleCurrentNum = simpleLastNum + simpleCurrentNum;
            currentNumDisplay.setText(String.valueOf(simpleCurrentNum));
            simpleLastNum = simpleCurrentNum;
            
            justOperated = true;
        }
        if (simpleOperation.equals("-")) {
            if (justOperated == false) {
                justOperatedNum = simpleCurrentNum;
                
            }
            
            simpleCurrentNum = simpleLastNum - simpleCurrentNum;
            currentNumDisplay.setText(String.valueOf(simpleCurrentNum));
            simpleLastNum = simpleCurrentNum;
            
            justOperated = true;
        }
        if (simpleOperation.equals("*")) {
            if (justOperated == false) {
                justOperatedNum = simpleCurrentNum;
                
            }
            
            simpleCurrentNum = simpleLastNum * simpleCurrentNum;
            currentNumDisplay.setText(String.valueOf(simpleCurrentNum));
            simpleLastNum = simpleCurrentNum;
            
            justOperated = true;
        }
        if (simpleOperation.equals("/")) {
            if (justOperated == false) {
                justOperatedNum = simpleCurrentNum;
                
            }
            
            simpleCurrentNum = simpleLastNum / simpleCurrentNum;
            currentNumDisplay.setText(String.valueOf(simpleCurrentNum));
            simpleLastNum = simpleCurrentNum;
            
            justOperated = true;
        }
    }//GEN-LAST:event_buttonEqualsMouseClicked

    private void buttonEqualsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEqualsMousePressed
        // TODO add your handling code here:
        buttonEquals.setBackground(lightRed);
    }//GEN-LAST:event_buttonEqualsMousePressed

    private void buttonEqualsMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonEqualsMouseReleased
        // TODO add your handling code here:
        buttonEquals.setBackground(red);
    }//GEN-LAST:event_buttonEqualsMouseReleased

    private void button0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button0MouseClicked
        // TODO add your handling code here:
        updateNumber(0);
    }//GEN-LAST:event_button0MouseClicked

    private void button0MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button0MousePressed
        // TODO add your handling code here:
        button0.setBackground(lightRed);
    }//GEN-LAST:event_button0MousePressed

    private void button0MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button0MouseReleased
        // TODO add your handling code here:
        button0.setBackground(red);
    }//GEN-LAST:event_button0MouseReleased

    private void buttonDecimalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDecimalMouseClicked
        // TODO add your handling code here:
        
        decimalMode = true;
        
    }//GEN-LAST:event_buttonDecimalMouseClicked

    private void buttonDecimalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDecimalMousePressed
        // TODO add your handling code here:
        buttonDecimal.setBackground(lightRed);
    }//GEN-LAST:event_buttonDecimalMousePressed

    private void buttonDecimalMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDecimalMouseReleased
        // TODO add your handling code here:
        buttonDecimal.setBackground(red);
    }//GEN-LAST:event_buttonDecimalMouseReleased

    private void buttonNegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonNegMouseClicked
        // TODO add your handling code here:
        simpleLastNum = simpleCurrentNum;
        simpleOperation = "*";
        simpleCurrentNum = -1;
        justOperated = false;
        buttonEqualsMouseClicked(null);
    }//GEN-LAST:event_buttonNegMouseClicked

    private void buttonNegMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonNegMousePressed
        // TODO add your handling code here:
        buttonNeg.setBackground(lightRed);
    }//GEN-LAST:event_buttonNegMousePressed

    private void buttonNegMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonNegMouseReleased
        // TODO add your handling code here:
        buttonNeg.setBackground(red);
    }//GEN-LAST:event_buttonNegMouseReleased

    private void buttonAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAddMouseClicked
        // TODO add your handling code here:
        doOperation("+");
    }//GEN-LAST:event_buttonAddMouseClicked

    private void buttonAddMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAddMousePressed
        // TODO add your handling code here:
        buttonAdd.setBackground(lightRed);
    }//GEN-LAST:event_buttonAddMousePressed

    private void buttonAddMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAddMouseReleased
        // TODO add your handling code here:
        buttonAdd.setBackground(red);
    }//GEN-LAST:event_buttonAddMouseReleased

    private void button3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button3MouseClicked
        // TODO add your handling code here:
        updateNumber(3);
    }//GEN-LAST:event_button3MouseClicked

    private void button3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button3MousePressed
        // TODO add your handling code here:
        button3.setBackground(lightRed);
    }//GEN-LAST:event_button3MousePressed

    private void button3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button3MouseReleased
        // TODO add your handling code here:
        button3.setBackground(red);
    }//GEN-LAST:event_button3MouseReleased

    private void button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseClicked
        // TODO add your handling code here:
        updateNumber(1);
    }//GEN-LAST:event_button1MouseClicked

    private void button1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MousePressed
        // TODO add your handling code here:
        button1.setBackground(lightRed);
    }//GEN-LAST:event_button1MousePressed

    private void button1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseReleased
        // TODO add your handling code here:
        button1.setBackground(red);
    }//GEN-LAST:event_button1MouseReleased

    private void buttonSubtractMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSubtractMouseClicked
        // TODO add your handling code here:
        doOperation("-");
    }//GEN-LAST:event_buttonSubtractMouseClicked

    private void buttonSubtractMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSubtractMousePressed
        // TODO add your handling code here:
        buttonSubtract.setBackground(lightRed);
    }//GEN-LAST:event_buttonSubtractMousePressed

    private void buttonSubtractMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonSubtractMouseReleased
        // TODO add your handling code here:
        buttonSubtract.setBackground(red);
    }//GEN-LAST:event_buttonSubtractMouseReleased

    private void button6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button6MouseClicked
        // TODO add your handling code here:
        updateNumber(6);
    }//GEN-LAST:event_button6MouseClicked

    private void button6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button6MousePressed
        // TODO add your handling code here:
        button6.setBackground(lightRed);
    }//GEN-LAST:event_button6MousePressed

    private void button6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button6MouseReleased
        // TODO add your handling code here:
        button6.setBackground(red);
    }//GEN-LAST:event_button6MouseReleased

    private void button4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button4MouseClicked
        // TODO add your handling code here:
        updateNumber(4);
    }//GEN-LAST:event_button4MouseClicked

    private void button4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button4MousePressed
        // TODO add your handling code here:
        button4.setBackground(lightRed);
    }//GEN-LAST:event_button4MousePressed

    private void button4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button4MouseReleased
        // TODO add your handling code here:
        button4.setBackground(red);
    }//GEN-LAST:event_button4MouseReleased

    private void button2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button2MouseClicked
        // TODO add your handling code here:
        updateNumber(2);
    }//GEN-LAST:event_button2MouseClicked

    private void button2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button2MousePressed
        // TODO add your handling code here:
        button2.setBackground(lightRed);
    }//GEN-LAST:event_button2MousePressed

    private void button2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button2MouseReleased
        // TODO add your handling code here:
        button2.setBackground(red);
    }//GEN-LAST:event_button2MouseReleased

    private void buttonMultiplyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMultiplyMouseClicked
        // TODO add your handling code here:
        doOperation("*");
    }//GEN-LAST:event_buttonMultiplyMouseClicked

    private void buttonMultiplyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMultiplyMousePressed
        // TODO add your handling code here:
        buttonMultiply.setBackground(lightRed);
    }//GEN-LAST:event_buttonMultiplyMousePressed

    private void buttonMultiplyMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMultiplyMouseReleased
        // TODO add your handling code here:
        buttonMultiply.setBackground(red);
    }//GEN-LAST:event_buttonMultiplyMouseReleased

    private void button9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button9MouseClicked
        // TODO add your handling code here:
        updateNumber(9);
    }//GEN-LAST:event_button9MouseClicked

    private void button9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button9MousePressed
        // TODO add your handling code here:
        button9.setBackground(lightRed);
    }//GEN-LAST:event_button9MousePressed

    private void button9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button9MouseReleased
        // TODO add your handling code here:
        button9.setBackground(red);
    }//GEN-LAST:event_button9MouseReleased

    private void button8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button8MouseClicked
        // TODO add your handling code here:
        updateNumber(8);
    }//GEN-LAST:event_button8MouseClicked

    private void button8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button8MousePressed
        // TODO add your handling code here:
        button8.setBackground(lightRed);
    }//GEN-LAST:event_button8MousePressed

    private void button8MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button8MouseReleased
        // TODO add your handling code here:
        button8.setBackground(red);
    }//GEN-LAST:event_button8MouseReleased

    private void button5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button5MouseClicked
        // TODO add your handling code here:
        updateNumber(5);
    }//GEN-LAST:event_button5MouseClicked

    private void button5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button5MousePressed
        // TODO add your handling code here:
        button5.setBackground(lightRed);
    }//GEN-LAST:event_button5MousePressed

    private void button5MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button5MouseReleased
        // TODO add your handling code here:
        button5.setBackground(red);
    }//GEN-LAST:event_button5MouseReleased

    private void button7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button7MouseClicked
        // TODO add your handling code here:
        updateNumber(7);
    }//GEN-LAST:event_button7MouseClicked

    private void button7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button7MousePressed
        // TODO add your handling code here:
        button7.setBackground(lightRed);
    }//GEN-LAST:event_button7MousePressed

    private void button7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button7MouseReleased
        // TODO add your handling code here:
        button7.setBackground(red);
    }//GEN-LAST:event_button7MouseReleased

    private void buttonDELMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDELMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDELMouseClicked

    private void buttonDELMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDELMousePressed
        // TODO add your handling code here:
        buttonDEL.setBackground(lightRed);
    }//GEN-LAST:event_buttonDELMousePressed

    private void buttonDELMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDELMouseReleased
        // TODO add your handling code here:
        buttonDEL.setBackground(red);
    }//GEN-LAST:event_buttonDELMouseReleased

    private void buttonDivideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDivideMouseClicked
        // TODO add your handling code here:
        doOperation("/");
    }//GEN-LAST:event_buttonDivideMouseClicked

    private void buttonDivideMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDivideMousePressed
        // TODO add your handling code here:
        buttonDivide.setBackground(lightRed);
    }//GEN-LAST:event_buttonDivideMousePressed

    private void buttonDivideMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDivideMouseReleased
        // TODO add your handling code here:
        buttonDivide.setBackground(red);
    }//GEN-LAST:event_buttonDivideMouseReleased

    private void buttonCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCMouseClicked
        // TODO add your handling code here:
        simpleLastNum = 0;
        lastNumDisplay.setText(String.valueOf(simpleLastNum));
        simpleCurrentNum = 0;
        currentNumDisplay.setText(String.valueOf(simpleCurrentNum));
    }//GEN-LAST:event_buttonCMouseClicked

    private void buttonCMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCMousePressed
        // TODO add your handling code here:
        buttonC.setBackground(lightRed);
    }//GEN-LAST:event_buttonCMousePressed

    private void buttonCMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCMouseReleased
        // TODO add your handling code here:
        buttonC.setBackground(red);
    }//GEN-LAST:event_buttonCMouseReleased

    private void buttonCEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCEMouseClicked
        // TODO add your handling code here:
        simpleCurrentNum = 0;
    }//GEN-LAST:event_buttonCEMouseClicked

    private void buttonCEMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCEMousePressed
        // TODO add your handling code here:
        buttonCE.setBackground(lightRed);
    }//GEN-LAST:event_buttonCEMousePressed

    private void buttonCEMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCEMouseReleased
        // TODO add your handling code here:
        buttonCE.setBackground(red);
    }//GEN-LAST:event_buttonCEMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainClass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainClass().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel button0;
    private javax.swing.JLabel button1;
    private javax.swing.JLabel button2;
    private javax.swing.JLabel button3;
    private javax.swing.JLabel button4;
    private javax.swing.JLabel button5;
    private javax.swing.JLabel button6;
    private javax.swing.JLabel button7;
    private javax.swing.JLabel button8;
    private javax.swing.JLabel button9;
    private javax.swing.JLabel buttonAdd;
    private javax.swing.JLabel buttonC;
    private javax.swing.JLabel buttonCE;
    private javax.swing.JLabel buttonDEL;
    private javax.swing.JLabel buttonDecimal;
    private javax.swing.JLabel buttonDivide;
    private javax.swing.JLabel buttonEquals;
    private javax.swing.JLabel buttonMultiply;
    private javax.swing.JLabel buttonNeg;
    private javax.swing.JLabel buttonSubtract;
    private javax.swing.JLabel currentNumDisplay;
    private javax.swing.JLabel lastNumDisplay;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JLabel scientificButton;
    private javax.swing.JLabel simpleButton;
    private javax.swing.JPanel simpleCalc;
    // End of variables declaration//GEN-END:variables

    @Override
    public void keyTyped(KeyEvent arg0) {
        //System.out.println("hi");
    }

    @Override
    public void keyPressed(KeyEvent arg0) {
        char keyPressed = arg0.getKeyChar();

        if (keyPressed == 'a') {
            System.out.println(simpleLastNum);
            System.out.println(simpleCurrentNum);
        }
        if (Character.isDigit(keyPressed)) {
            updateNumber(Character.getNumericValue(keyPressed));
        }
        if (keyPressed == '+') {
            buttonAddMouseClicked(null);
        }
        if (keyPressed == '-') {
            buttonSubtractMouseClicked(null);
        }
        if (keyPressed == '*' || keyPressed == 'x') {
            buttonMultiplyMouseClicked(null);
        }
        if (keyPressed == '/') {
            buttonDivideMouseClicked(null);
        }
        if (keyPressed == '=' || arg0.getKeyCode() == KeyEvent.VK_ENTER) {
            buttonEqualsMouseClicked(null);
        }
    }

    @Override
    public void keyReleased(KeyEvent arg0) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    public void updateNumber(int number) {
        if (justOperated == true) {
            simpleCurrentNum = 0;
        }
        justOperated = false;
        if (currentNumDisplay.getText().length() <= 16) {
            if (decimalMode == false) {
                simpleCurrentNum = simpleCurrentNum * 10;
                simpleCurrentNum = simpleCurrentNum + number;
                currentNumDisplay.setText(String.valueOf(simpleCurrentNum));
            }
            if (decimalMode == true) {
                String temp = String.valueOf(simpleCurrentNum);
                temp = temp + String.valueOf(number);
                simpleCurrentNum = Long.valueOf(temp);
                currentNumDisplay.setText(String.valueOf(simpleCurrentNum));
            }
        }


        
    }
    
    public void doOperation(String op) {
        simpleOperation = op;
        simpleLastNum = simpleCurrentNum;
        lastNumDisplay.setText(String.valueOf(simpleLastNum) + " " + simpleOperation + " ");
        simpleCurrentNum = 0;
    }

}
